### ISSUE TITLE
Bill frequency codes?

### ISSUE THREAD

**Issue by patwater** [California-Data-Collaborative/Open-Water-Rate-Specification#1]
What do the codes for bill frequency mean?  i.e. the 1 in "bill_frequency: 1"

**Comment by christophertull** [comment]
Supposed to indicate 1 for monthly, 2 for bimonthly (every 2 months) etc. One thought would be to change this to a text field indicating "monthly", "bimonthly", etc.

Obviously the specification is a little bare-bones at the moment ;)

**Comment by patwater** [comment]
Roger rogue leader.  Sounds great!
