### ISSUE TITLE
Targeted Google search to source water rates?

### ISSUE THREAD

**Issue by vr00n** [California-Data-Collaborative/Open-Water-Rate-Specification#12]
["water rates" intitle:"city of" "california"] (https://www.google.com/search?num=100&espv=2&q=%22water+rates%22+intitle%3A%22city+of%22+%22california%22&oq=%22water+rates%22+intitle%3A%22city+of%22+%22california%22&gs_l=serp.3...75242.87305.0.87573.32.28.4.0.0.0.135.2346.17j8.25.0....0...1c.1.64.serp..5.15.1415...0j0i22i30k1j30i10k1._Z3aHqCJ15c)

**Comment by patwater** [comment]
Wow this is pretty pro.  Maybe worth including in a prep email to the attendees @vykster ?

**Comment by vykster** [comment]
@patwater @vr00n nice. yeah we'll include it in materials.
