### ISSUE TITLE
FOUND: Raftelis Water Rate Survey

### ISSUE THREAD

**Issue by vr00n** [California-Data-Collaborative/Open-Water-Rate-Specification#13]
**[2015 Water Rate Survey](http://ca-nv-awwa.org/CANV/downloads/2016/CANVRateSurvey2015.pdf)**

**[2013 Water Rate Survey](http://ca-nv-awwa.org/canv/downloads/2015/CANVRateSurvey2013.pdf)**

RFC conducts a biennial national water and wastewater rate survey in partnership with the American Water Works Association (AWWA), a nonprofit professional association dedicated to providing high-quality technical information to its water utility members and general public. RFC also conducts a biennial water rate survey in California and Nevada in collaboration with the California-Nevada section of AWWA, as well as water rate surveys in Florida and Arizona. RFC is nationally recognized for its financial and management consulting practice for water, wastewater, and stormwater utilities. 

[Additionally see their excel template for 2016 Water and Wastewater Rate Survey](http://www.awwa.org/Portals/0/files/resources/water%20utility%20management/water%20and%20wastewater%20rates/nosearch/2016%20Water%20Wastewater%20Rate%20Survey.xlsx)

**Comment by vr00n** [comment]
I have transcribed the rate surveys and added
[here](https://docs.google.com/spreadsheets/d/1jYCjwdYdAqyL4UzKaIkvfW_gj0086U74hrX2VqEfiR0/edit#gid=11585614)
@vipassana can you please: 

1. Compare and sanity check this excel transcription with the source PDFs (2015 and 2013 Water rate surveys).
2.  Clean COUNTY column - its not as simple as just filling down. Seems hairier.


FYI - 2015 survey contains Waste water rates as well. THis is out of scope for now

**Comment by christophertull** [comment]
Cool! Maybe use as validation data for OWRS analysis?

**Comment by vr00n** [comment]
hey @vincent-hebble - any chance we can incorporate this into the CARTO we built for OpenDataSpectacular?

**Comment by christophertull** [comment]
What is it you would like to see displayed @vr00n ?

**Comment by vr00n** [comment]
Oops
[](https://www.mindmeister.com/810718167)

**Comment by christophertull** [comment]
Nice. Mindmeister is a good format for displaying the specification imo. Not sure about how we would incorporate into the Carto map though. Maybe we could link to it in our follow-up blog post?

**Comment by vr00n** [comment]
Oops sorry mates - I meant incorporating the G-SHEET with the Raftelis survey into the CARTO Map.

https://docs.google.com/spreadsheets/d/1jYCjwdYdAqyL4UzKaIkvfW_gj0086U74hrX2VqEfiR0/edit#gid=11585614

**Comment by patwater** [comment]
Huh is that mindmeister suggesting refactoring OWRS into a version 2 with a different way of specifying a bill?

**Comment by vr00n** [comment]
@patwater apologies - please refer https://github.com/California-Data-Collaborative/Open-Water-Rate-Specification/issues/59

re: this issue - vipassana to clean up county column this week

The goal here is to create an OWRS map that  captures our efforts + H/Ts RAFTELIS work because it's non-trivial work really.
