### ISSUE TITLE
Triunfo Sanitation District folder name

### ISSUE THREAD

**Issue by victorsette** [California-Data-Collaborative/Open-Water-Rate-Specification#192]
The OWRS file for [Triunfo Sanitation District / Oak Park Water Service](https://github.com/California-Data-Collaborative/Open-Water-Rate-Specification/blob/master/full_utility_rates/California/Triunfo%20Sanitation%20District/%20Oak%20Park%20Water%20Service%20-%200/07-01-2017.owrs) is not being parsed correctly in the analysis because of the "/ " in the directory name. 

Is there an easy way to change the directory name or is it easier to delete this directory and create a new branch to merge?

**Comment by christophertull** [comment]
IMO just make a new branch and name the utility "Oak Park Water Service" since they are the retailer owned by triunfo

**Comment by victorsette** [comment]
Solved!
