### ISSUE TITLE
IDEA: California open water rate pricing project spectacular!

### ISSUE THREAD

**Issue by patwater** [California-Data-Collaborative/Open-Water-Rate-Specification#3]
The open water pricing project aims to standardize every retail water rate in California into a common data format.  The resulting inter-operable machine readable data will make basic questions that currently require digging through outdated reports as easy as a google search. Such questions include: what was the average price of water paid by Californians last month?  How does that vary by income and ethnicity?  

Currently those questions are answered through time intensive manual surveys.  CaDC project manager Patrick Atwater conducted one such survey in 2006 by personally calling over 200 of Southern California's 281 water retailers!  Yet in the age of Google, such questions do not need to be manually parsed through mind numbing processes.  We have remarkable machines that can do that for us. 

The Open Water Rate Specification (OWRS) has been prototyped and piloted with members of the CaDC coalition.  You can see the latest work on our open source GitHub repository here: https://github.com/California-Data-Collaborative/Open-Water-Rate-Specification  This specification is ready to be implemented with more utilities, increasing the transparency of water rates as well as powering CaDC open source analytics to support effective water management.  

This event will catalyze us to engage more volunteers to deploy this specification for more water agencies.  Each of California's 411 major urban retailers will need to be encoded.  Our network of civic technologists would be instrumental in helping achieve that though our budget is currently just to provide analytics for current CaDC agencies.

**Comment by christophertull** [comment]
Could also be an interesting project for university partners. The [Utility Rate Database](http://en.openei.org/wiki/Utility_Rate_Database) is maintained by NREL and Illinois State University with DoE funding.

I could imagine there must be researchers out there who would kill for the chance to examine pricing trends across CA to create something like this:

![image](https://cloud.githubusercontent.com/assets/9061565/20732804/34dae842-b645-11e6-92d7-cd6486c50ed2.png)

**Comment by patwater** [comment]
Yup :) http://www.efc.sog.unc.edu/project/utility-financial-sustainability-and-rates-dashboards

**Comment by patwater** [comment]
@christophertull zero rush though maybe an explanatory video is order to brief potential folks on why OWRS is critical and how to fill it out?

**Comment by patwater** [comment]
Note international Open Data Day doesn't have an LA or NY chapter: http://wiki.opendataday.org/2017/City_Events H/T :)

CC @christophertull @clairehxq @vipassana @b44p @amyoshino

**Comment by patwater** [comment]
More context: https://docs.google.com/document/d/1fBuisDTIiBAz9u2tr7sgv6GdDLOV_aHbafjqHXSkNB0/edit#heading=h.h0h4y9n56bc8

**Comment by b44p** [comment]
[I just want to say that this is exactly what drove innovation in the Financial Sector.](http://www.fixtradingcommunity.org/pg/structure/tech-specs/implementation-guide/implementation-guide)
