### ISSUE TITLE
OWRS v2

### ISSUE THREAD

**Issue by vr00n** [California-Data-Collaborative/Open-Water-Rate-Specification#59]
Capturing good thoughts post spectacular and working towards spec-ing out improvements.

Towards an OWRS v2:

https://www.mindmeister.com/810718167

![image](https://user-images.githubusercontent.com/4397663/29212314-ecd04138-7e6b-11e7-8153-9b502fd33f94.png)

We approached this by reverse engineering a canonical water bill and borrowed concepts from other "utility" bills such as cell-phone bill which also has "connection type" (4G vs 3G is basically meter_size). 

Also proposes *generic fixed rate* and *usage-based* components that could be used to explain rate granularity across: 

- space (zoning, parcel types, other geographies)
- time ( seasonal, time of day etc.) 
- usage (volumetric tiers)
-  and other effects (surcharges etc.)

Key is abstract the water jargon towards a common vocabulary to capture and communicate statewide water rate structures

cc @vincent-hebble @vipassana

**Comment by patwater** [comment]
@vr00n isn't this already incorporated _"generic fixed rate"_ and _"generic usage rate"_?

**Comment by patwater** [comment]
CC @christophertull

**Comment by christophertull** [comment]
I am not sure I am really grasping the proposed changes. Maybe could use a brief call at some point to explain?

I am all for standardizing our vocabulary as much as possible and defining explicit categories. However there is a trade-off to making the vocabulary more general in that it takes the spec farther from what is present in the PDF/webpage. 

Rather than renaming the `service_charge` and `commodity_charge`, I could see `service_charge` being one instance of a "fixed rate component" while a `commodity_charge` is an instance of a "usage-based rate component" ? This is already logically true, but doesn't fit into our docs or specification in any way as of yet.

**Comment by vr00n** [comment]
@christophertull and I riffed over this for a good hour and noodled with different approaches on how best to future-proof the spec.

Some concerns at the moment are
1. Version Controlling the spec  - There is no tag that describes the version of the spec. 
2. if we need to update the spec by adding a new tag then

- how do we updated the parser?
- how do we updated the owrs files before the change?

3. Determining when to make a change in the spec.
 - changing tag nomenclature. (ex: changing service_charge to fixed_components)
 - adding other structures that can be supported. (ex: adding some new surcharge)

**Comment by patwater** [comment]
Roger.  @vr00n re 1  so are you suggesting that the version of open water rate specification be included in the tool?  That's be good though some of that is included in effective date.

Re 2 OWRS plays nicely with the rate parser so arbitrary tags automatically get included.  This is a sample of what results from `read_owrs_file` for LADWP:

`$rate_structure$FIRE_SERVICE$flat_rate
[1] 1.331

$rate_structure$FIRE_SERVICE$commodity_charge
[1] "flat_rate*usage_ccf"

$rate_structure$FIRE_SERVICE$bill
[1] "service_charge+commodity_charge"`

3 what's the logic for changing to fixed_components?  Note a meter service charge is a type of fixed component and not you can other specific fixed charges like a new development capacity charge by just using that tag say `new_dev_capacity` or similar.  

I can appreciate the urge for generalizability though note there's already an energy rate specification for example and the structure of energy is much different.  It involves not just usage charges though much more complicated second order issues like time: http://en.openei.org/services/doc/rest/util_rates/?version=3  

Realize that's part of your motivation at the top of this issue though note that largely distracts from the immediate task at hand to standardize all of California's water rate information.

@vr00n by the way how many full OWRS files have you gone through yet?
