### ISSUE TITLE
Thoughts on process for QA/QCing OWRS files being created?

### ISSUE THREAD

**Issue by patwater** [California-Data-Collaborative/Open-Water-Rate-Specification#7]
Maybe putting two sets of eyes on each one

**Comment by christophertull** [comment]
Ideal process would be pull requests approved by someone experienced with OWRS

**Comment by vishelar** [comment]
Maybe documenting the issues and problems faced so that they can be referenced in the future.

**Comment by vr00n** [comment]
This is being tacked by @vipassana while creating the OWRS definition file. The aim is to create a non-ambiguous vocabulary for the water rates.
