### ISSUE TITLE
IDEA: what if we added a bill calculator as an incentive for utilities to participate

### ISSUE THREAD

**Issue by patwater** [California-Data-Collaborative/Open-Water-Rate-Specification#90]
Something similar to: https://www.mnwd.com/billcalculator

**Comment by patwater** [comment]
Develop a bill calculator leveraging Open Water Rate Specification (OWRS) data. This tool would allow users to put in their address and water use for a given month and see the estimated bill for that month. Extensions include comparing that to other water utilities.

**Comment by christophertull** [comment]
Yeah honestly this would be pretty cool. If mainly as a way to get utility staff on board with maintaining updated (an accurate) OWRS files
